export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'


export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_FINISHED = 'REQUEST_FINISHED';

export const LOGIN_REQUESTED = 'login-requested';
export const LOGIN_REQUESTED = 'login-succeeded';
export const LOGIN_FAILED = 'login-failed';
export const LOGIN_COMPLETED = 'login-completed';

export const LOGOUT_REQUESTED = 'logout-requested';
export const LOGOUT_COMPLETED = 'logout-completed';

export const CHANGE_PASSWORD_REQUESTED = 'CHANGE_PASSWORD_REQUESTED';
export const CHANGE_PASSWORD_SUCCEEDED = 'CHANGE_PASSWORD_SUCCEEDED';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const PROFILE__REQUESTED = 'PROFILE__REQUESTED';
export const PROFILE__REQUESTED__SUCCEEDED = 'PROFILE__REQUESTED__SUCCEEDED';
export const PROFILE__REQUESTED__FAILED = 'PROFILE__REQUESTED__FAILED';



export const REGISTER__REQUESTED = 'REGISTER__REQUESTED';
export const REGISTER__REQUEST__SUCCEEDED = 'REGISTER__REQUEST__SUCCEEDED';
export const REGISTER__REQUEST__FAILED = 'REGISTER__REQUEST__FAILED';
