# Generated by Django 3.0.4 on 2020-03-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_restaurant', models.CharField(max_length=1000)),
                ('location_x', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('food_available_start_time', models.TimeField()),
                ('food_available_end_time', models.TimeField()),
                ('food_available', models.CharField(max_length=1000)),
                ('potential_allergies', models.CharField(max_length=1000)),
            ],
        ),
    ]
