# Generated by Django 3.0.4 on 2020-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location_y',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
